language: node_js
node_js:
  - "8.8.1"

before_script:
    - yarn

master:
  before_script:
    - echo "//registry.npmjs.org/:_authToken=${TOKEN_NPM}" > ~/.npmrc
    - echo "//registry.npmjs.org/:_password=${PASSWORD_NPM}" >> ~/.npmrc
    - echo "//registry.npmjs.org/:username=dleitee" >> ~/.npmrc
    - echo "//registry.npmjs.org/:email=dleitee@gmail.com" >> ~/.npmrc

script:
  - yarn test-version
  - yarn flow
  - yarn lint
  - yarn test

master:
  script:
    - yarn build:packages
    - npm publish

after_success:
  - yarn coveralls
